"""add project_custom_fields table

Revision ID: 5cf662c3691f
Revises: 9f852858cc1c
Create Date: 2026-03-12 17:14:37.945250
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5cf662c3691f'
down_revision: Union[str, None] = '9f852858cc1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('field_key', sa.String(length=50), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'SELECT', 'MULTI_SELECT', 'BOOLEAN', 'URL', name='fieldtype'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'field_key')
    )
    op.create_index(op.f('ix_project_custom_fields_project_id'), 'project_custom_fields', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_custom_fields_project_id'), table_name='project_custom_fields')
    op.drop_table('project_custom_fields')
    # ### end Alembic commands ###
