"""add task_dependencies table

Revision ID: 6d4d6a65be95
Revises: 5cf662c3691f
Create Date: 2026-03-12 17:19:30.630993
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d4d6a65be95'
down_revision: Union[str, None] = '5cf662c3691f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocking_task_id', sa.Integer(), nullable=False),
    sa.Column('blocked_task_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.Enum('BLOCKS', 'RELATES_TO', 'DUPLICATES', name='dependencytype'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('blocking_task_id != blocked_task_id'),
    sa.ForeignKeyConstraint(['blocked_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocking_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocking_task_id', 'blocked_task_id')
    )
    op.create_index(op.f('ix_task_dependencies_blocked_task_id'), 'task_dependencies', ['blocked_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_blocking_task_id'), 'task_dependencies', ['blocking_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_dependencies_blocking_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_blocked_task_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
