"""Add automation_rules table

Revision ID: e4ef3b49e85b
Revises: 6d4d6a65be95
Create Date: 2026-03-12 17:22:43.912315
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e4ef3b49e85b'
down_revision: Union[str, None] = '6d4d6a65be95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.Enum('STATUS_CHANGED', 'DUE_DATE_PASSED', 'TASK_CREATED', 'ALL_SUBTASKS_DONE', 'ASSIGNED_TO_CHANGED', name='triggertype'), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('action_type', sa.Enum('CHANGE_STATUS', 'ASSIGN_TO', 'CREATE_TASK', 'SEND_NOTIFICATION', 'SET_FIELD', name='actiontype'), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_triggered', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_rules_project_id'), 'automation_rules', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_rules_project_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
